 - hosts: all
   tasks:
   - name: Clone a github repository
     ansible.builtin.git:
       repo: git@github.com:pbmoses/aap_demo.git
       dest: C:\Users\IEUser\AppData\Local\Temp
       clone: yes
       update: yes
