#simple run of a powershell script. PMO

- name: reboot 
  hosts: all 
  
  tasks: 
    - name: Run basic PowerShell script
      ansible.windows.win_powershell:
      script: |
        echo "Hello World"
